---
devMode: # if devMode is true, it will override individual settings for development
  enabled: true
  # if enabled the following properties will be set
  exposeGlobalVariables: true

htmlBg: black # background color for letter boxing edges if aspect ratio is not 16:9
svgBg: white
hideUrlParameters: false
slideTransition:
  override: false # force slide transitions, regardless of implementation in illustrator
  fadeOut: 0.25
  fadeIn: 0.25
css:
  # will be used within the init process to to add style="cursor: pointer" to the given ids
  # this uses querySelectorAll in styleDefaults.ts
  # Syntax: [id^=startsWith][id$=endsWith]
  mousePointerObjects:
    [
      '[id^=link][id$=next]',
      '[id^=link][id$=headphones]',
      '[id^=link][id$=yes]',
      '[id^=link][id$=no]',
    ]
  # will be used within the init process to to add a zoom animation on hover
  scaleOnHoverObjects:
    [
      '[id^=link][id$=next]',
      '[id^=link][id$=headphones]',
      '[id^=link][id$=yes]',
      '[id^=link][id$=no]',
    ]
globals:
  defaultCulture: de-urban
  defaultSubjectId: demo
audio:
  type: mp3
  customAnimationTimes: # this will override the german default
    namibia:
      s-introduction: [4] # time in seeconds for appear animation
      s-human: [4, 2]
  cues:
    si-introduction: [0]

procedure:
  # use exact slide ids from Illustrator for values
  # The order defines the experiment order
  # If you create a nested array at the second level, the slides will be presented in random order
  de-urban:
    [
      s-introduction,
      s-cow,
      s-pig,
      [s-sheep, s-chicken, s-cat],
      s-dog,
      s-rabbit,
      s-goldfish,
      s-human,
      s-mc-intro,
      s-ball-animation,
      s-ball-practice,
      s-task,
      s-intro-boats,
    ]
  en-urban: [s-introduction, s-moral-circle, s-human, s-transition]
  na-urban: [s-introduction, s-moral-circle, s-human, s-transition]

dilemma:
  random: true
  # procedure: [
  #   - cat:
  #       random: false
  #       procedure: [asdf-adsf-, c-a-3 ]
  #   - cow:
  #       random: true
  #       procedure: [c-a-3, asdf-adsf-]
  #   - control:
  #       random: true
  #       procedure: [c-a-3, asdf-adsf-]
  # ]
interview:
  random: false
  order: [asdf-adsf-, c-a-3]
capacity:
  random: true
  order: [asdf-asdf, asfdsaf-asdasfd]
