---
devmode: # exposes global variables, and does other stuff
  on: false
  playbackRate: 1
htmlBg: black # background color for letter boxing edges if aspect ratio is not 16:9
svgBg: white
hideUrlParameters: false
slideTransition:
  override: true # force slide transitions
  fadeOut: 0.25
  fadeIn: 0.25
css:
  # will be used within the init process to to add style="cursor: pointer" to the given ids
  # this uses querySelectorAll in styleDefaults.ts
  # Syntax: [id^=startsWith][id$=endsWith]
  mousePointerObjects:
    [
      '#link-si-speaker',
      '[id^=link][id$=next]',
      '[id^=link][id$=headphones]',
      '[id^=link][id$=yes]',
      '[id^=link][id$=no]',
    ]
  # will be used within the init process to to add a zoom animation on hover
  scaleOnHoverObjects:
    [
      '#link-si-speaker',
      '[id^=link][id$=next]',
      '[id^=link][id$=headphones]',
      '[id^=link][id$=yes]',
      '[id^=link][id$=no]',
    ]
  pinda: # applies for pinda and neutral pinda videos
    height: '30%' # pinda height
    left: '0' # offset from left SVG edge, use 0 for none offset, otherwise px,%, etc. (e.g., '10px')
    bottom: '0' # offset from bottom SVG edge, use 0 for none offset, otherwise px,%, etc. (e.g., '10px')

globals:
  defaultSubjectId: demo
  defaultCulture: de-urban # possible keys from
  defaultBirthday: '2100-01-01'
  defaultCoupon: TESTCODE
  defaultPROLIFIC_PID: none
  adultThresholdAge: 12 # 11 = child, 12 = adult
  defaultGender: none
  defaultInput: userchoice-audio
  defaultDataTransfer: both
  slideGapDuration: 750 # delay for most slides before transitioning to next
  playAnimalYesNoAudio: 2
  playAnimalResponseFeedback: 1
  minimumTextInputLength: 4

procedure:
  # use exact slide ids from Illustrator for values
  # The order defines the experiment order
  # If you create a key with a sub array everything in the sub array will be randomized
  # You can nest only two levels deep
  de-urban:
    - s-introduction
    - s-intro-human-animals
    - animalOrder: [s-cow, s-pig, s-sheep, s-chicken, s-cat, s-dog, s-rabbit, s-goldfish, s-human]
    - s-mc-intro
    - s-ball-animation
    - s-ball-practice
    - s-task
    - s-meaning
    - s-intro-boats
    - s-practice-dilemma
    - s-dilemma-start
    - dilemmaOrder:
        - companionOrder:
            [
              s-1-hu-1-ca,
              s-2-hu-1-ca,
              s-1-hu-2-ca,
              s-10-hu-1-ca,
              s-1-hu-10-ca,
              s-100-hu-1-ca,
              s-1-hu-100-ca,
            ]
        - foodOrder:
            [
              s-1-hu-1-co,
              s-2-hu-1-co,
              s-1-hu-2-co,
              s-10-hu-1-co,
              s-1-hu-10-co,
              s-100-hu-1-co,
              s-1-hu-100-co,
            ]
        - controlOrder: [s-1-hu-10-hu, s-1-hu-10-na, s-1-hu-10-sp, s-1-ca-1-co]
    - s-motivation-dilemma3
    - s-qu-thoughts
    - s-qu-feelings
    - s-qu-difference
    - s-intro-ranking
    - rankingOrder:
        [
          s-qu-ranking-intelligence,
          s-qu-ranking-pain,
          s-qu-ranking-feelings,
          s-qu-ranking-similarity,
        ]
    - s-motivation-questions
    - s-qu-ownership
    - s-qu-ranking-exposure
    - s-qu-meat-fish
    - s-qu-egg-cheese-milk
    - s-intro-reasoning
    - reasoningOrder: [s-reasoning-1-hu-1-co, s-reasoning-1-hu-1-ca, s-reasoning-1-ca-1-co]
    - s-resolve-dilemma
    - s-end

  pe-rural:
    - s-introduction
    - s-intro-human-animals
    - animalOrder: [s-cow, s-pig, s-chicken, s-cat, s-dog, s-rabbit, s-turkey, s-parrot, s-humanpe]
    - s-mc-intro
    - s-ball-animation
    - s-ball-practice
    - s-task-pe
    - s-meaning
    - s-intro-boats
    - s-practice-dilemma
    - s-dilemma-start
    - dilemmaOrder:
        - companionOrder:
            [
              s-1-pe-1-do,
              s-2-pe-1-do,
              s-1-pe-2-do,
              s-10-pe-1-do,
              s-1-pe-10-do,
              s-100-pe-1-do,
              s-1-pe-100-do,
            ]
        - foodOrder:
            [
              s-1-pe-1-ch,
              s-2-pe-1-ch,
              s-1-pe-2-ch,
              s-10-pe-1-ch,
              s-1-pe-10-ch,
              s-100-pe-1-ch,
              s-1-pe-100-ch,
            ]
        - controlOrder: [s-1-pe-10-pe, s-1-pe-10-na, s-1-pe-10-sp, s-1-do-1-ch]
    - s-motivation-dilemma3
    - s-qu-thoughts
    - s-qu-feelings
    - s-qu-difference
    - s-intro-ranking
    - rankingOrder:
        [
          s-qu-ranking-intelligence-pe,
          s-qu-ranking-pain-pe,
          s-qu-ranking-feelings-pe,
          s-qu-ranking-similarity-pe,
        ]
    - s-motivation-questions
    - s-qu-ownership
    - s-qu-ranking-exposure-pe
    - s-qu-meat-fish
    - s-qu-egg-cheese-milk
    - s-intro-reasoning
    - reasoningOrder: [s-reasoning-1-pe-1-ch, s-reasoning-1-pe-1-do, s-reasoning-1-do-1-ch]
    - s-resolve-dilemma
    - s-end

  idj-urban:
    - s-introduction
    - s-intro-human-animals
    - animalOrder:
        [s-cow, s-catfish, s-goat, s-chicken, s-cat, s-dog, s-parrot, s-goldfish, s-humanidj]
    - s-mc-intro
    - s-ball-animation
    - s-ball-practice
    - s-task-idj
    - s-meaning
    - s-intro-boats
    - s-practice-dilemma
    - s-dilemma-start
    - dilemmaOrder:
        - companionOrder:
            [
              s-1-ij-1-ca,
              s-2-ij-1-ca,
              s-1-ij-2-ca,
              s-10-ij-1-ca,
              s-1-ij-10-ca,
              s-100-ij-1-ca,
              s-1-ij-100-ca,
            ]
        - foodOrder:
            [
              s-1-ij-1-ch,
              s-2-ij-1-ch,
              s-1-ij-2-ch,
              s-10-ij-1-ch,
              s-1-ij-10-ch,
              s-100-ij-1-ch,
              s-1-ij-100-ch,
            ]
        - controlOrder: [s-1-ij-10-ij, s-1-ij-10-na, s-1-ij-10-sp, s-1-ca-1-ch]
    - s-motivation-dilemma3
    - s-qu-thoughts
    - s-qu-feelings
    - s-qu-difference
    - s-intro-ranking
    - rankingOrder:
        [
          s-qu-ranking-intelligence-idj,
          s-qu-ranking-pain-idj,
          s-qu-ranking-feelings-idj,
          s-qu-ranking-similarity-idj,
        ]
    - s-motivation-questions
    - s-qu-ownership
    - s-qu-ranking-exposure-idj
    - s-qu-meat-fish
    - s-qu-egg-cheese-milk
    - s-intro-reasoning
    - reasoningOrder: [s-reasoning-1-ij-1-ch, s-reasoning-1-ij-1-ca, s-reasoning-1-ca-1-ch]
    - s-resolve-dilemma
    - s-end

  nam-rural:
    - s-introduction
    - s-intro-human-animals
    - animalOrder:
        [s-duiker, s-kudu, s-giraffe, s-jackal, s-cat, s-dog, s-chicken, s-goat, s-humannam]
    - s-mc-intro
    - s-ball-animation
    - s-ball-practice
    - s-task-nam
    - s-meaning
    - s-intro-boats
    - s-practice-dilemma-nam
    - s-dilemma-start
    - dilemmaOrder:
        - companionOrder:
            [
              s-1-nm-1-do,
              s-2-nm-1-do,
              s-1-nm-2-do,
              s-10-nm-1-do,
              s-1-nm-10-do,
              s-100-nm-1-do,
              s-1-nm-100-do,
            ]
        - foodOrder:
            [
              s-1-nm-1-du,
              s-2-nm-1-du,
              s-1-nm-2-du,
              s-10-nm-1-du,
              s-1-nm-10-du,
              s-100-nm-1-du,
              s-1-nm-100-du,
            ]
        - controlOrder: [s-1-nm-10-nm, s-1-nm-10-st, s-1-nm-10-sa, s-1-do-1-du]
    - s-motivation-dilemma3
    - s-qu-thoughts
    - s-qu-feelings
    - s-qu-difference
    - s-intro-ranking
    - rankingOrder:
        [
          s-qu-ranking-intelligence-nam,
          s-qu-ranking-pain-nam,
          s-qu-ranking-feelings-nam,
          s-qu-ranking-similarity-nam,
        ]
    - s-motivation-questions
    - s-qu-ownership
    - s-qu-ranking-exposure-nam
    - s-qu-meat-fish
    - s-qu-egg-cheese-milk
    - s-intro-reasoning
    - reasoningOrder: [s-reasoning-1-nm-1-du, s-reasoning-1-nm-1-do, s-reasoning-1-do-1-du]
    - s-resolve-dilemma
    - s-end

  zm-rural:
    - s-introduction
    - s-intro-human-animals
    - animalOrder: [s-cat, s-dog, s-cat2, s-dog2, s-chicken, s-cow, s-goat, s-hare, s-humanzm]
    - s-mc-intro
    - s-ball-animation
    - s-ball-practice
    - s-task-zm
    - s-meaning
    - s-intro-boats
    - s-practice-dilemma-zm
    - s-dilemma-start
    - dilemmaOrder:
        - companionOrder:
            [
              s-1-zm-1-do,
              s-2-zm-1-do,
              s-1-zm-2-do,
              s-10-zm-1-do,
              s-1-zm-10-do,
              s-100-zm-1-do,
              s-1-zm-100-do,
            ]
        - foodOrder:
            [
              s-1-zm-1-ch,
              s-2-zm-1-ch,
              s-1-zm-2-ch,
              s-10-zm-1-ch,
              s-1-zm-10-ch,
              s-100-zm-1-ch,
              s-1-zm-100-ch,
            ]
        - controlOrder: [s-1-zm-10-zm, s-1-zm-10-st, s-1-zm-10-sa, s-1-do-1-ch]
    - s-motivation-dilemma3
    - s-qu-thoughts
    - s-qu-feelings
    - s-qu-difference
    - s-intro-ranking
    - rankingOrder:
        [
          s-qu-ranking-intelligence-zm,
          s-qu-ranking-pain-zm,
          s-qu-ranking-feelings-zm,
          s-qu-ranking-similarity-zm,
        ]
    - s-motivation-questions
    - s-qu-ownership
    - s-qu-ranking-exposure-zm
    - s-qu-meat-fish
    - s-qu-egg-cheese-milk
    - s-intro-reasoning
    - reasoningOrder: [s-reasoning-1-zm-1-ch, s-reasoning-1-zm-1-do, s-reasoning-1-do-1-ch]
    - s-resolve-dilemma
    - s-end
