---
devMode: # if devMode is true, it will override individual settings for development
  enabled: true
  # if enabled the following properties will be set
  exposeGlobalVariables: true

htmlBg: black # background color for letter boxing edges if aspect ratio is not 16:9
svgBg: white
hideUrlParameters: false
slideTransition:
  override: true # force slide transitions, regardless of implementation in illustrator
  fadeOut: 0.25
  fadeIn: 0.25
css:
  # will be used within the init process to to add style="cursor: pointer" to the given ids
  # todo make this regexable
  mousePointerObjects:
    [
      link-si-next,
      link-si-headphones,
      link-s-cow-headphones,
      link-s-cow-yes,
      link-s-cow-no,
      link-s-pig-headphones,
      link-s-pig-yes,
      link-s-pig-no,
      link-s-sheep-headphones,
      link-s-sheep-yes,
      link-s-sheep-no,
      link-s-chicken-headphones,
      link-s-chicken-yes,
      link-s-chicken-no,
      link-s-cat-headphones,
      link-s-cat-yes,
      link-s-cat-no,
      link-s-dog-headphones,
      link-s-dog-yes,
      link-s-dog-no,
      link-s-rabbit-headphones,
      link-s-rabbit-yes,
      link-s-rabbit-no,
      link-s-goldfish-headphones,
      link-s-goldfish-yes,
      link-s-goldfish-no,
    ]
  # will be used within the init process to to add a zoom animation on hover
  scaleOnHoverObjects:
    [
      link-si-next,
      link-si-headphones,
      link-s-cow-headphones,
      link-s-cow-yes,
      link-s-cow-no,
      link-s-pig-headphones,
      link-s-pig-yes,
      link-s-pig-no,
      link-s-sheep-headphones,
      link-s-sheep-yes,
      link-s-sheep-no,
      link-s-chicken-headphones,
      link-s-chicken-yes,
      link-s-chicken-no,
      link-s-cat-headphones,
      link-s-cat-yes,
      link-s-cat-no,
      link-s-dog-headphones,
      link-s-dog-yes,
      link-s-dog-no,
      link-s-rabbit-headphones,
      link-s-rabbit-yes,
      link-s-rabbit-no,
      link-s-goldfish-headphones,
      link-s-goldfish-yes,
      link-s-goldfish-no,
    ]
globals:
  defaultCulture: deUrban # use camelCase (de-urban → deUrban)
  defaultSubjectId: demo
audio:
  type: mp3
  customAnimationTimes: # this will override the german default
    namibia:
      s-introduction: [4] # time in seeconds for appear animation
      s-human: [4, 2]
  cues:
    si-introduction: [0]

procedure:
  # use camelCase for culture key names (de-urban → deUrban) and use exact
  # slide ids from Illustrator for values
  # todo use objects to specify more props per slide such as random
  deUrban: [
      # s-introduction,
      # s-transition-1,
      # s-humans,
      # s-transition-2,
      # s-cow,
      # s-pig,
      # s-sheep,
      # s-chicken,
      # s-cat,
      # s-dog,
      # s-rabbit,
      # s-goldfish,
      # s-transition-3,
      # s-mc-intro,
      # s-ball-animation,
      s-ball-practice,
    ]
  enUrban: [s-introduction, s-moral-circle, s-humans, s-transition]
  naUrban: [s-introduction, s-moral-circle, s-humans, s-transition]

dilemma:
  random: true
  # procedure: [
  #   - cat:
  #       random: false
  #       procedure: [asdf-adsf-, c-a-3 ]
  #   - cow:
  #       random: true
  #       procedure: [c-a-3, asdf-adsf-]
  #   - control:
  #       random: true
  #       procedure: [c-a-3, asdf-adsf-]
  # ]
interview:
  random: false
  order: [asdf-adsf-, c-a-3]
capacity:
  random: true
  order: [asdf-asdf, asfdsaf-asdasfd]
