---
devMode: # if devMode is true, it will override individual settings for development
  enabled: true
  # if enabled the following properties will be set
  exposeGlobalVariables: true

htmlBg: 'black' # background color for letter boxing edges if aspect ratio is not 16:9
svgBg: 'white'
globals:
  initialSlideColor: '#3F3F3F' # css color for initial slide
  finalSlideColor: 'black' # css color for ending slide
  defaultPopulation: de-de
