---
devMode: # if devMode is true, it will override individual settings for development
  enabled: true
  # if enabled the following properties will be set
  exposeGlobalVariables: true

htmlBg: black # background color for letter boxing edges if aspect ratio is not 16:9
svgBg: white
hideUrlParameters: false
slideTransition:
  override: false # force slide transitions
  fadeOut: 0.25
  fadeIn: 0.25
css:
  # will be used within the init process to to add style="cursor: pointer" to the given ids
  # this uses querySelectorAll in styleDefaults.ts
  # Syntax: [id^=startsWith][id$=endsWith]
  mousePointerObjects:
    [
      '#link-si-speaker',
      '[id^=link][id$=next]',
      '[id^=link][id$=headphones]',
      '[id^=link][id$=yes]',
      '[id^=link][id$=no]',
    ]
  # will be used within the init process to to add a zoom animation on hover
  scaleOnHoverObjects:
    [
      '#link-si-speaker',
      '[id^=link][id$=next]',
      '[id^=link][id$=headphones]',
      '[id^=link][id$=yes]',
      '[id^=link][id$=no]',
    ]
globals:
  defaultCulture: de-urban # possible keys from
  defaultSubjectId: demo
  defaultAgeGroup: child # or adult
  defaultInput: userchoice
  animalSlidesGap: 750 # delay in milliseconds after animal slides
  playAnimalYesNoAudio: 2
  playAnimalResponseFeedback: 1
  minimumTextInputLength: 4

procedure:
  # use exact slide ids from Illustrator for values
  # The order defines the experiment order
  # If you create a nested array at the second level, the slides will be presented in random order
  de-urban: [
      s-introduction,
      # s-intro-human-animals,
      # s-cow,
      [s-cow, s-giraffe, s-pig, s-sheep, s-chicken, s-cat, s-dog, s-rabbit, s-goldfish, s-human],
      s-mc-intro,
      s-ball-animation,
      s-ball-practice,
      s-task,
      s-meaning,
      s-intro-boats,
      s-practice-dilemma,
      # # [
      # #   [s-1-hu-1-ca, s-2-hu-1-ca, s-1-hu-2-ca, s-10-hu-1-ca, s-1-hu-10-ca, s-100-hu-1-ca]
      # # dynamic transiton slide 1
      # #   [s-1-hu-1-co, s-2-hu-1-co, s-1-hu-2-co, s-10-hu-1-co, s-1-hu-10-co, s-100-hu-1-co, s-1-hu-100-co]
      # # dynamic transiton slide 2
      # #   [s-c-1-hu-10-hu, s-c-1-hu-10-na, s-c-1-hu-10-sp, s-c-1-ca-1-co]
      # # ]
      # s-motivation-dilemma3,
      s-1-hu-1-ca,
      s-2-hu-1-ca,
      s-1-hu-2-ca,
      s-10-hu-1-ca,
      s-1-hu-10-ca,
      s-100-hu-1-ca,
      s-1-hu-1-co,
      s-2-hu-1-co,
      s-1-hu-2-co,
      s-10-hu-1-co,
      s-1-hu-10-co,
      s-100-hu-1-co,
      s-1-hu-100-co,
      s-c-1-hu-10-hu,
      s-c-1-hu-10-na,
      s-c-1-hu-10-sp,
      s-c-1-ca-1-co,
      s-qu-thoughts,
      s-qu-feelings,
      s-qu-difference,
      # # [s-qu-ranking-intelligence, s-qu-ranking-pain, s-qu-ranking-feelings, s-qu-ranking-similarity]
      s-qu-ranking-intelligence,
      s-qu-ranking-pain,
      s-qu-ranking-feelings,
      s-qu-ranking-similarity,
      s-qu-ownership,
      s-qu-ranking-exposure,
      s-qu-meat-fish,
      s-qu-egg-cheese-milk,
      # # [s-reasoning-1-hu-1-co, s-reasoning-1-hu-1-ca, s-reasoning-1-ca-1-co]
      s-reasoning-1-hu-1-co,
      s-reasoning-1-hu-1-ca,
      s-reasoning-1-ca-1-co,
      s-resolve-dilemma,
      s-end,
    ]
  en-urban: [s-introduction, s-moral-circle, s-human]
  na-urban: [s-introduction, s-moral-circle, s-human]
